#!/usr/bin/env node
/**
 * Vendor the app's webfonts into `public/fonts/` and generate
 * `src/styles/fonts.css` from the result.
 *
 * WHY THIS EXISTS: `index.css` used to `@import` Inter and JetBrains Mono from
 * fonts.googleapis.com. OpenHuman is an offline-capable desktop app, so on a
 * cold start without a network the CSS import fails and the entire UI renders
 * in a system fallback face — a first-run regression nobody sees in dev,
 * because dev machines are online and the font is already cached.
 *
 * Re-run after changing weights or families:
 *   node scripts/fetch-fonts.mjs
 *
 * It is deliberately a checked-in generator rather than a build step: fetching
 * from a third party during every build would put a network dependency back
 * into the thing this removes.
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

// A modern desktop UA, so Google serves woff2 rather than legacy formats.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { family: 'Inter', slug: 'inter', weights: [300, 400, 500, 600, 700] },
  { family: 'JetBrains Mono', slug: 'jetbrains-mono', weights: [300, 400, 500, 600] },
];

const FONT_DIR = new URL('../public/fonts/', import.meta.url);
const OUT_CSS = new URL('../src/styles/fonts.css', import.meta.url);

/** Parses Google's CSS into `{ subset, weight, url, unicodeRange }` records. */
function parseFaces(css, family) {
  const faces = [];
  const blocks = css.split('@font-face');
  let pendingSubset = 'latin';

  for (const block of blocks) {
    const subsetMatch = block.match(/\/\*\s*([a-z0-9-]+)\s*\*\//i);
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const url = block.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (subsetMatch) pendingSubset = subsetMatch[1];
    if (!weight || !url || !unicodeRange) continue;

    // The comment naming a subset precedes the block it labels, so the match
    // inside this block actually names the NEXT one.
    const subset = faces.length === 0 ? 'latin' : pendingSubset;
    faces.push({ family, subset, weight: Number(weight), url, unicodeRange: unicodeRange.trim() });
  }
  return faces;
}

/** Re-derives subsets from the comment that precedes each block. */
function parseFacesOrdered(css, family) {
  const faces = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/gi;
  let match;
  while ((match = re.exec(css)) !== null) {
    const [, subset, body] = match;
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
    const url = body.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!weight || !url || !unicodeRange) continue;
    faces.push({ family, subset, weight: Number(weight), url, unicodeRange: unicodeRange.trim() });
  }
  return faces;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  for (const existing of await readdir(FONT_DIR).catch(() => [])) {
    if (existing.endsWith('.woff2')) await rm(new URL(existing, FONT_DIR));
  }

  const chunks = [
    `/*\n * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n *\n * Self-hosted so the desktop app renders its real typefaces offline. Every\n * unicode-range is preserved from Google's own CSS, so a Latin-only session\n * still downloads only the Latin subsets.\n */\n`,
  ];

  for (const { family, slug, weights } of FAMILIES) {
    const href = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, '+')}:wght@${weights.join(';')}&display=swap`;
    const res = await fetch(href, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${family}: ${res.status} ${res.statusText}`);
    const css = await res.text();

    const faces = parseFacesOrdered(css, family);
    if (faces.length === 0) throw new Error(`${family}: parsed no @font-face blocks`);

    for (const face of faces) {
      const filename = `${slug}-${face.weight}-${face.subset}.woff2`;
      const fontRes = await fetch(face.url, { headers: { 'User-Agent': UA } });
      if (!fontRes.ok) throw new Error(`${filename}: ${fontRes.status}`);
      const bytes = Buffer.from(await fontRes.arrayBuffer());
      await writeFile(new URL(filename, FONT_DIR), bytes);

      chunks.push(
        `@font-face {\n` +
          `  font-family: '${family}';\n` +
          `  font-style: normal;\n` +
          `  font-weight: ${face.weight};\n` +
          `  font-display: swap;\n` +
          `  src: url('/fonts/${filename}') format('woff2');\n` +
          `  unicode-range: ${face.unicodeRange};\n` +
          `}\n`
      );
    }
    console.log(`${family}: ${faces.length} faces`);
  }

  await writeFile(OUT_CSS, chunks.join('\n'));
  console.log(`wrote ${join('src', 'styles', 'fonts.css')}`);
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
